service: serverless-work
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    API_LARAVEL: ${env:API_LARAVEL, 'http://127.0.0.1:8000/'}

constructs:
  jobs:
    type: queue
    worker:
      handler: index.consumer

functions:
  producer:
    handler: index.producer
    events:
      - httpApi:
          method: post
          path: /produce
    environment:
      QUEUE_URL: ${construct:jobs.queueUrl}

plugins:
  - serverless-lift
  - serverless-offline
